#############################################################################
# Makefile for building zn5Cal
# Generated by tmake at 12:43, 2012/07/06
#     Project: zn5Cal
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	$(CROSS_COMPILE)gcc
CXX	=	$(CROSS_COMPILE)g++
CFLAGS	=	-pipe -Wall -W -O3 -DNO_DEBUG
CXXFLAGS=	-pipe -DQWS -fno-exceptions -fno-rtti -Wall -W -O3 -DNO_DEBUG
INCPATH	=	-I$(QTDIR)/include -I$(QTDIR)/extern3rd/include
LINK	=	$(CROSS_COMPILE)gcc
LFLAGS	=	-Wl,-rpath $(QTDIR)/lib -Wl,-rpath $(QTDIR)/target/lib
LIBS	=	$(SUBLIBS) -L$(QTDIR)/lib -L$(QTDIR)/extern3rd/lib -lm -lqte-mt -lezxappbase -lezxam $(LIBLINK)
MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic

TAR	=	tar -cf
GZIP	=	gzip -9f

####### Files

HEADERS =	Data.h \
		mZWidget.h
SOURCES =	Data.cpp \
		mZWidget.cpp \
		main.cpp
OBJECTS =	.obj/Data.o \
		.obj/mZWidget.o \
		.obj/main.o
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	
OBJMOC	=	
DIST	=	
TARGET	=	zn5Cal
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

tmake: Makefile

Makefile: zn5Cal.pro
	tmake zn5Cal.pro -o Makefile

dist:
	$(TAR) zn5Cal.tar zn5Cal.pro $(SOURCES) $(HEADERS) $(INTERFACES) $(DIST)
	$(GZIP) zn5Cal.tar

clean:
	-rm -f $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	-rm -f *~ core

####### Sub-libraries


###### Combined headers


####### Compile

.obj/Data.o: Data.cpp \
		Data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Data.o Data.cpp

.obj/mZWidget.o: mZWidget.cpp \
		mZWidget.h \
		debug.h \
		Data.h \
		key.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mZWidget.o mZWidget.cpp

.obj/main.o: main.cpp \
		mZWidget.h \
		debug.h \
		Data.h \
		key.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

install: $(TARGET)
	sudo cp $(TARGET) $(TFCARD)/mpkgbox/zn5Cal
